// ─── Shared curriculum data & helpers ───────────────────────────
// Used by dashboard, profile, certificate, lesson

export const CURRICULUM = {
  html: {
    label:"HTML", color:"#e34c26", icon:"⬡",
    levels:[
      { id:"html-1", title:"What is HTML?",         xp:100, objective:"Understand HTML structure and write your first webpage.",       theory:`HTML uses <strong>tags</strong> wrapped in angle brackets to define elements. Every page needs: DOCTYPE, html, head, and body.`, task:"Create a page with a heading, a paragraph, and your name in a &lt;strong&gt; tag.", hints:["Use &lt;h1&gt; for the heading","Wrap your name in &lt;strong&gt;","Content goes inside &lt;body&gt;"], starter:`<!DOCTYPE html>\n<html lang="en">\n  <head><title>My First Page</title></head>\n  <body>\n    <!-- Write your code below -->\n\n  </body>\n</html>`, check:(c)=>c.includes("<h1")&&c.includes("<p")&&c.includes("<strong") },
      { id:"html-2", title:"Headings & Paragraphs", xp:120, objective:"Use all 6 heading levels and paragraph tags correctly.",        theory:`HTML has 6 headings: <strong>&lt;h1&gt;</strong> (largest) through <strong>&lt;h6&gt;</strong>. <strong>&lt;p&gt;</strong> wraps paragraphs. <strong>&lt;hr&gt;</strong> draws a horizontal rule.`, task:"Build a page with h1, h2, h3 headings and two paragraphs separated by a horizontal rule.", hints:["&lt;hr&gt; is self-closing","Only one &lt;h1&gt; per page","&lt;br&gt; adds a line break"], starter:`<!DOCTYPE html>\n<html lang="en">\n<head><title>Headings</title></head>\n<body>\n  <!-- Add headings and paragraphs -->\n\n</body>\n</html>`, check:(c)=>c.includes("<h1")&&c.includes("<h2")&&c.includes("<hr") },
      { id:"html-3", title:"Links & Navigation",    xp:150, objective:"Create hyperlinks that open in new tabs and link to sections.", theory:`<strong>&lt;a href&gt;</strong> creates links. <strong>target="_blank"</strong> opens in a new tab. <strong>href="#id"</strong> jumps to a section.`, task:"Create 3 links: google.com (new tab), github.com, and one jumping to a section id='about'.", hints:["target=\"_blank\" opens new tab","Sections need an id attribute","Add rel=\"noopener\" for security"], starter:`<!DOCTYPE html>\n<html lang="en">\n<head><title>Links</title></head>\n<body>\n  <!-- Links here -->\n\n  <section id="about"><h2>About</h2></section>\n</body>\n</html>`, check:(c)=>c.includes('href="https://')&&c.includes('target="_blank"')&&c.includes('href="#about"') },
      { id:"html-4", title:"Images & Media",        xp:150, objective:"Embed images with proper alt text.",                            theory:`<strong>&lt;img src alt&gt;</strong> embeds images. Always include <strong>alt</strong> for accessibility. Wrap in <strong>&lt;figure&gt;</strong> with <strong>&lt;figcaption&gt;</strong> for semantic meaning.`, task:"Add an image with alt text, inside a figure with a caption, width 300px.", hints:["img is self-closing","alt text describes the image","figcaption goes inside figure"], starter:`<!DOCTYPE html>\n<html lang="en">\n<head><title>Images</title></head>\n<body>\n  <!-- Add your figure here -->\n\n</body>\n</html>`, check:(c)=>c.includes("<figure")&&c.includes("alt=")&&c.includes("<figcaption") },
      { id:"html-5", title:"Lists",                 xp:120, objective:"Create ordered, unordered, and nested lists.",                  theory:`<strong>&lt;ul&gt;</strong> = bullet list. <strong>&lt;ol&gt;</strong> = numbered list. Both use <strong>&lt;li&gt;</strong> for items. Lists can be nested.`, task:"Build a recipe page with an ingredients list (ul) and steps (ol) with at least one nested list.", hints:["Nest a &lt;ul&gt; inside an &lt;li&gt;","ol items auto-number","ul = unordered, ol = ordered"], starter:`<!DOCTYPE html>\n<html lang="en">\n<head><title>Lists</title></head>\n<body>\n  <h1>My Recipe</h1>\n  <!-- Add lists here -->\n\n</body>\n</html>`, check:(c)=>c.includes("<ul")&&c.includes("<ol")&&c.includes("<li") },
      { id:"html-6", title:"Tables",                xp:180, objective:"Build structured data tables.",                                 theory:`Tables use <strong>&lt;table&gt;</strong>, <strong>&lt;thead&gt;</strong>, <strong>&lt;tbody&gt;</strong>, <strong>&lt;tr&gt;</strong>, <strong>&lt;th&gt;</strong>, <strong>&lt;td&gt;</strong>. Use <strong>colspan</strong> to merge cells.`, task:"Create a schedule table with days as columns and time slots as rows. Merge at least one cell.", hints:["thead = header row","tbody = data rows","colspan merges columns"], starter:`<!DOCTYPE html>\n<html lang="en">\n<head><title>Tables</title></head>\n<body>\n  <table border="1">\n    <caption>Weekly Schedule</caption>\n    <!-- thead and tbody here -->\n\n  </table>\n</body>\n</html>`, check:(c)=>c.includes("<thead")&&c.includes("<tbody")&&c.includes("colspan") },
      { id:"html-7", title:"Forms & Inputs",        xp:200, objective:"Build a complete form with validation attributes.",             theory:`<strong>&lt;form&gt;</strong> collects input. Match <strong>label for</strong> to <strong>input id</strong>. Types: text, email, password, checkbox. Add <strong>required</strong> to validate.`, task:"Build a registration form: name (required), email (required), password (min 8), age (number), terms checkbox.", hints:["label for= must match input id=","type=\"email\" validates email","required prevents empty submit"], starter:`<!DOCTYPE html>\n<html lang="en">\n<head><title>Forms</title></head>\n<body>\n  <form>\n    <h2>Register</h2>\n    <!-- Add fields here -->\n    <button type="submit">Create Account</button>\n  </form>\n</body>\n</html>`, check:(c)=>c.includes('type="email"')&&c.includes('required')&&c.includes('type="checkbox"') },
      { id:"html-8", title:"Semantic HTML",         xp:200, objective:"Structure a webpage using semantic HTML5 elements.",            theory:`Use semantic tags: <strong>&lt;header&gt;</strong>, <strong>&lt;nav&gt;</strong>, <strong>&lt;main&gt;</strong>, <strong>&lt;article&gt;</strong>, <strong>&lt;aside&gt;</strong>, <strong>&lt;footer&gt;</strong> instead of generic divs.`, task:"Build a blog layout using only semantic elements — no divs for structure.", hints:["header = top of page","nav = navigation","footer = bottom of page"], starter:`<!DOCTYPE html>\n<html lang="en">\n<head><title>Semantic HTML</title></head>\n<body>\n  <!-- header, nav, main, article, aside, footer -->\n\n</body>\n</html>`, check:(c)=>c.includes("<header")&&c.includes("<main")&&c.includes("<footer")&&c.includes("<nav") }
    ]
  },
  css: {
    label:"CSS", color:"#264de4", icon:"◈",
    levels:[
      { id:"css-1", title:"Selectors & Properties", xp:100, objective:"Apply styles using element, class, and ID selectors.", theory:`CSS selectors: <strong>element</strong> (p), <strong>.class</strong>, <strong>#id</strong>. Written as: <code>selector { property: value; }</code>`, task:"Style a page: body background #111, h1 color cyan, p font-size 18px, .highlight class with yellow background.", hints:["Use hex colors like #00d4ff","font-size uses px or rem",".highlight targets that class"], starter:`<!DOCTYPE html>\n<html>\n<head>\n<style>\n  /* Your CSS here */\n\n</style>\n</head>\n<body>\n  <h1>Styled Page</h1>\n  <p>Regular paragraph</p>\n  <p class="highlight">Highlighted</p>\n</body>\n</html>`, check:(c)=>c.includes("background")&&c.includes("color")&&c.includes(".highlight") },
      { id:"css-2", title:"Box Model",              xp:150, objective:"Understand margin, padding, border, and box-sizing.", theory:`Box model (inside out): <strong>content → padding → border → margin</strong>. Use <strong>box-sizing: border-box</strong> to include padding/border in width.`, task:"Create 3 boxes 200px wide with 20px padding, 2px border, different margins, box-sizing: border-box.", hints:["box-sizing: border-box is best practice","margin: auto centers block elements","border: 2px solid red shorthand"], starter:`<!DOCTYPE html>\n<html>\n<head>\n<style>\n  * { box-sizing: border-box; }\n  /* Style your boxes */\n\n</style>\n</head>\n<body>\n  <div class="box">Box 1</div>\n  <div class="box">Box 2</div>\n  <div class="box">Box 3</div>\n</body>\n</html>`, check:(c)=>c.includes("padding")&&c.includes("border")&&c.includes("margin") },
      { id:"css-3", title:"Flexbox",                xp:200, objective:"Build flexible layouts with Flexbox.", theory:`<strong>display: flex</strong> on a container. Key: <strong>justify-content</strong> (main axis), <strong>align-items</strong> (cross axis), <strong>gap</strong>, <strong>flex-wrap</strong>.`, task:"Build a nav bar (logo left, links right) and a 3-card row using flexbox.", hints:["justify-content: space-between spreads items","align-items: center vertically centers","gap adds spacing between items"], starter:`<!DOCTYPE html>\n<html>\n<head>\n<style>\n  body { margin:0; background:#111; color:white; font-family:sans-serif; }\n  /* Add flexbox styles */\n\n</style>\n</head>\n<body>\n  <nav>\n    <div class="logo">ENOVA</div>\n    <div class="links"><a href="#" style="color:white">Home</a><a href="#" style="color:white;margin-left:16px">About</a></div>\n  </nav>\n  <div class="cards">\n    <div class="card">Card 1</div>\n    <div class="card">Card 2</div>\n    <div class="card">Card 3</div>\n  </div>\n</body>\n</html>`, check:(c)=>c.includes("display: flex")&&c.includes("justify-content") },
      { id:"css-4", title:"CSS Grid",               xp:220, objective:"Create complex 2D layouts with CSS Grid.", theory:`<strong>display: grid</strong>. <strong>grid-template-columns</strong> defines columns. <strong>grid-column: 1 / -1</strong> spans full width. <strong>gap</strong> adds spacing.`, task:"Build a layout: full-width header, 2-col content (main + sidebar), full-width footer using grid.", hints:["grid-template-columns: 2fr 1fr makes 2:1 ratio","grid-column: 1 / -1 spans all columns","gap adds space between grid cells"], starter:`<!DOCTYPE html>\n<html>\n<head>\n<style>\n  body { margin:0; font-family:sans-serif; }\n  .layout { display:grid; min-height:100vh; }\n  header,footer { background:#333; color:white; padding:20px; }\n  main { background:#f0f0f0; padding:20px; }\n  aside { background:#ddd; padding:20px; }\n</style>\n</head>\n<body>\n  <div class="layout">\n    <header>Header</header>\n    <main>Main</main>\n    <aside>Sidebar</aside>\n    <footer>Footer</footer>\n  </div>\n</body>\n</html>`, check:(c)=>c.includes("display: grid")&&c.includes("grid-template") },
      { id:"css-5", title:"Animations",             xp:220, objective:"Add smooth transitions and keyframe animations.", theory:`<strong>transition</strong> animates property changes on events. <strong>@keyframes</strong> defines animation sequences. <strong>animation</strong> applies them with name, duration, and iteration.`, task:"Create a button that changes color on hover (transition), and a pulsing circle with @keyframes.", hints:["transition: all 0.3s ease is a good default","@keyframes uses from/to or 0%/100%","animation-iteration-count: infinite loops forever"], starter:`<!DOCTYPE html>\n<html>\n<head>\n<style>\n  body { display:flex; flex-direction:column; align-items:center; gap:40px; padding:60px; background:#111; }\n  .btn { padding:12px 28px; background:#00d4ff; color:#000; border:none; border-radius:8px; font-size:16px; cursor:pointer; }\n  .circle { width:80px; height:80px; border-radius:50%; background:#7c3aed; }\n  /* Add transitions and @keyframes */\n\n</style>\n</head>\n<body>\n  <button class="btn">Hover Me</button>\n  <div class="circle"></div>\n</body>\n</html>`, check:(c)=>c.includes("transition")&&c.includes("@keyframes")&&c.includes("animation") },
      { id:"css-6", title:"Responsive Design",      xp:250, objective:"Build layouts that work on all screen sizes.", theory:`<strong>@media (max-width: 768px)</strong> targets screens under 768px. Mobile-first = write mobile styles first, add desktop styles in media queries. Use %, rem, vw instead of fixed px.`, task:"Build a 3-column card grid that collapses to 1 column on mobile (under 768px).", hints:["Start with mobile styles first","@media (max-width: 768px) targets small screens","grid-template-columns: 1fr makes single column"], starter:`<!DOCTYPE html>\n<html>\n<head>\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<style>\n  body { margin:0; padding:20px; font-family:sans-serif; background:#111; color:white; }\n  .grid { /* Add responsive grid */ }\n  .card { background:#1e1e2e; padding:24px; border-radius:12px; }\n  /* Add @media query */\n\n</style>\n</head>\n<body>\n  <div class="grid">\n    <div class="card">Card 1</div>\n    <div class="card">Card 2</div>\n    <div class="card">Card 3</div>\n  </div>\n</body>\n</html>`, check:(c)=>c.includes("@media")&&c.includes("max-width") }
    ]
  },
  js: {
    label:"JavaScript", color:"#f7df1e", icon:"⬟",
    levels:[
      { id:"js-1", title:"Variables & Data Types",  xp:100, objective:"Declare variables and understand JavaScript's primitive types.", theory:`<strong>const</strong> = can't reassign. <strong>let</strong> = can reassign. Types: string, number, boolean, null, undefined. Template literals: <code>\`Hello \${name}\`</code>`, task:"Declare variables for a user profile (name, age, isStudent), then display them in HTML using template literals.", hints:["const for values that won't change","let for values that will","Template literals use backticks"], starter:`<!DOCTYPE html>\n<html>\n<body>\n  <div id="output"></div>\n  <script>\n    const name = "Your Name";\n    let age = 20;\n    // Add more variables\n\n    document.getElementById('output').innerHTML = \`Name: \${name}\`;\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes("const")&&c.includes("let")&&c.includes("getElementById") },
      { id:"js-2", title:"Functions",               xp:150, objective:"Write regular functions, arrow functions, and understand parameters.", theory:`<strong>function</strong> declarations are hoisted. <strong>Arrow functions</strong>: <code>const fn = (x) => x * 2</code>. Use <strong>return</strong> to send values back. Default params: <code>function greet(name = 'World')</code>`, task:"Write 3 functions: greet(name), add(a,b), and an arrow function square(n). Call all 3 and display results.", hints:["Arrow: const square = (n) => n * n","Default params: function greet(name='World')","Return sends a value back"], starter:`<!DOCTYPE html>\n<html>\n<body>\n  <div id="output"></div>\n  <script>\n    function greet(name) { return "Hello, " + name; }\n    // Add add(a,b) and arrow square(n)\n\n    document.getElementById('output').innerHTML = greet("World");\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes("function")&&c.includes("=>")&&c.includes("return") },
      { id:"js-3", title:"DOM Manipulation",        xp:200, objective:"Select, modify, and create HTML elements with JavaScript.", theory:`<strong>querySelector</strong> and <strong>getElementById</strong> select elements. Modify with <strong>textContent</strong>, <strong>innerHTML</strong>, <strong>classList</strong>. Create with <strong>createElement</strong> + <strong>appendChild</strong>.`, task:"Build a dynamic list: input + button that adds items to a ul. Items should delete on click.", hints:["createElement creates a new element","appendChild adds it to the DOM","addEventListener('click', fn) listens for clicks"], starter:`<!DOCTYPE html>\n<html>\n<head><style>body{font-family:sans-serif;padding:20px}li{cursor:pointer;padding:8px;margin:4px;background:#f0f0f0;border-radius:4px}li:hover{background:#ffcccc}</style></head>\n<body>\n  <input id="inp" placeholder="Add item..."/><button id="addBtn">Add</button>\n  <ul id="list"></ul>\n  <script>\n    document.getElementById('addBtn').addEventListener('click', function() {\n      // Create li, set text, add click to remove, append to list\n    });\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes("createElement")&&c.includes("addEventListener")&&c.includes("appendChild") },
      { id:"js-4", title:"Events",                  xp:180, objective:"Handle user events: clicks, keyboard, and input events.", theory:`<strong>addEventListener(event, callback)</strong> handles events. Common events: click, keydown, keyup, input, submit. The <strong>event object</strong> has info: event.target, event.key, event.preventDefault().`, task:"Build a color picker: clicking buttons changes background color. Press 'R' to reset to black.", hints:["event.key gives the pressed key","document.body.style.background sets background","data attributes store values: element.dataset.color"], starter:`<!DOCTYPE html>\n<html>\n<head><style>body{transition:background 0.3s;padding:40px;font-family:sans-serif}.btn{width:50px;height:50px;border:none;border-radius:50%;cursor:pointer;margin:8px}</style></head>\n<body>\n  <h2>Click a color or press 'R' to reset</h2>\n  <button class="btn" style="background:#00d4ff" data-color="#00d4ff"></button>\n  <button class="btn" style="background:#7c3aed" data-color="#7c3aed"></button>\n  <button class="btn" style="background:#f59e0b" data-color="#f59e0b"></button>\n  <script>\n    // Add click and keydown event listeners\n\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes("addEventListener")&&c.includes("click")&&c.includes("keydown") },
      { id:"js-5", title:"Arrays & Loops",          xp:200, objective:"Work with arrays using map, filter, and forEach.", theory:`<strong>filter(fn)</strong> returns matching items. <strong>map(fn)</strong> transforms each item. <strong>forEach(fn)</strong> loops without returning. <strong>push</strong> adds, <strong>pop</strong> removes last item.`, task:"Given a products array, filter items under $50, then map to get uppercase names, then display.", hints:["filter returns a new array","map transforms each item","Combine: array.filter(...).map(...)"], starter:`<!DOCTYPE html>\n<html>\n<body>\n  <div id="output"></div>\n  <script>\n    const products = [\n      {name:"Keyboard",price:79},{name:"Mouse",price:35},\n      {name:"Monitor",price:299},{name:"Headset",price:45},{name:"USB Hub",price:25}\n    ];\n    // 1. Filter under $50\n    // 2. Map to uppercase names\n    // 3. Display in #output\n    document.getElementById('output').innerHTML = products.length + " products";\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes(".filter(")&&c.includes(".map(") },
      { id:"js-6", title:"Objects",                 xp:200, objective:"Create objects, use methods, and destructure properties.", theory:`Objects store key-value pairs. Access: <strong>obj.key</strong> or <strong>obj['key']</strong>. <strong>Destructuring</strong>: <code>const {name, age} = user</code>. <strong>Spread</strong>: <code>{...obj, newProp: val}</code>. Methods are functions inside objects.`, task:"Create a student object with greet() and getGrade() methods. Destructure its properties and display a profile card.", hints:["Methods: greet() { return 'Hi ' + this.name; }","Destructure: const { name, grade } = student","this refers to the object itself"], starter:`<!DOCTYPE html>\n<html>\n<body>\n  <div id="profile"></div>\n  <script>\n    const student = {\n      name: "Alex", age: 20, grade: 92,\n      greet() { return "Hi, I'm " + this.name; }\n      // Add getGrade() method\n    };\n    const { name, age } = student;\n    document.getElementById('profile').innerHTML = \`\${name} - \${student.greet()}\`;\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes("greet")&&c.includes("const {") },
      { id:"js-7", title:"Fetch & APIs",            xp:280, objective:"Fetch data from a public API and display it dynamically.", theory:`<strong>fetch(url)</strong> makes HTTP requests. Use <strong>async/await</strong> for clean code. Parse JSON with <strong>response.json()</strong>. Always wrap in <strong>try/catch</strong> for error handling.`, task:"Fetch 5 random users from https://randomuser.me/api/?results=5 and display their photo, name, and email.", hints:["async function + await fetch(url)","await response.json() parses the data","response.data.results holds the users array"], starter:`<!DOCTYPE html>\n<html>\n<head><style>body{font-family:sans-serif;padding:20px;background:#111;color:white}.users{display:flex;flex-wrap:wrap;gap:16px}.card{background:#1e1e2e;padding:20px;border-radius:12px;text-align:center;width:160px}.card img{border-radius:50%;width:80px}</style></head>\n<body>\n  <h1>Random Users</h1>\n  <div id="loading" style="color:#00d4ff">Loading...</div>\n  <div class="users" id="users"></div>\n  <script>\n    async function fetchUsers() {\n      try {\n        // fetch from https://randomuser.me/api/?results=5\n        // parse json, loop results, create cards\n      } catch(e) { document.getElementById('loading').textContent = 'Error: ' + e.message; }\n    }\n    fetchUsers();\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes("fetch(")&&c.includes("await")&&c.includes(".json()") },
      { id:"js-8", title:"Local Storage",           xp:220, objective:"Persist data in the browser with localStorage.", theory:`<strong>localStorage.setItem(key, value)</strong> saves data. <strong>getItem(key)</strong> reads it. <strong>removeItem(key)</strong> deletes. Always <strong>JSON.stringify()</strong> objects to save, <strong>JSON.parse()</strong> to read.`, task:"Build a notes app: textarea + save button. Notes persist after page refresh. Show notes with delete buttons.", hints:["JSON.stringify converts objects to strings","JSON.parse converts strings back to objects","Load saved notes on page load"], starter:`<!DOCTYPE html>\n<html>\n<head><style>body{font-family:sans-serif;padding:20px;max-width:500px}textarea{width:100%;height:100px;padding:12px;box-sizing:border-box;margin-bottom:8px}.note{background:#f5f5f5;padding:12px;margin:8px 0;border-radius:8px;display:flex;justify-content:space-between}</style></head>\n<body>\n  <h2>My Notes</h2>\n  <textarea id="noteInput" placeholder="Write a note..."></textarea>\n  <button id="saveBtn">Save Note</button>\n  <div id="notesList"></div>\n  <script>\n    // Load notes, save notes, display notes with delete\n    // Use localStorage with JSON.stringify/parse\n  <\/script>\n</body>\n</html>`, check:(c)=>c.includes("localStorage")&&c.includes("JSON.stringify")&&c.includes("JSON.parse") }
    ]
  }
};

export const TRACKS = ["html","css","js"];

export function getTrackProgress(trackKey, completedLessons) {
  const levels = CURRICULUM[trackKey].levels;
  const done = levels.filter(l => completedLessons.includes(l.id)).length;
  return { done, total: levels.length, pct: Math.round((done / levels.length) * 100) };
}

export function getNextLesson(completedLessons) {
  for (const t of TRACKS) {
    for (const l of CURRICULUM[t].levels) {
      if (!completedLessons.includes(l.id)) return l;
    }
  }
  return null;
}

export function getAllLessons() {
  return TRACKS.flatMap(t => CURRICULUM[t].levels);
}

export function getLessonById(id) {
  for (const t of TRACKS) {
    const l = CURRICULUM[t].levels.find(l => l.id === id);
    if (l) return l;
  }
  return null;
}
